name: Verify User in CODEOWNERS

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Check CODEOWNERS
        id: check-owners
        run: |
          # Extract the GitHub username of the user who triggered the workflow
          GITHUB_USERNAME=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          
          # Get the CODEOWNERS file content
          CODEOWNERS_CONTENT=$(cat .github/CODEOWNERS)
          
          # Check if the GitHub username exists in CODEOWNERS
          if [[ $CODEOWNERS_CONTENT =~ (^|[[:space:]])@$GITHUB_USERNAME($|[[:space:]]) ]]; then
            echo "User $GITHUB_USERNAME is mentioned in CODEOWNERS"
            exit 0
          else
            echo "User $GITHUB_USERNAME is not mentioned in CODEOWNERS"
            exit 1
          fi
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
