name: Only CODEOWNERS can Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  merge_if_authorized:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check CODEOWNERS
        run: |
          # Get the author of the pull request
          AUTHOR=${{ github.actor }}

          # Check if the author is in the CODEOWNERS file
          if grep -q "$AUTHOR" .github/CODEOWNERS; then
            echo "Authorized to merge"
          else
            echo "Not authorized to merge"
            exit 1
          fi
        working-directory: ${{ github.workspace }}

      - name: Merge PR
        if: success() # Only merge if the previous step was successful
        run: |
          # Merge the PR using GitHub CLI
          gh pr merge "${{ github.event.pull_request.number }}" --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
