name: Only CODEOWNERS can Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  merge_if_authorized:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the authenticated GitHub user
        id: get_github_user
        run: |
          AUTHENTICATED_USER=$(curl -s -H "Authorization: token ${{ github.token }}" \
              https://api.github.com/user | jq -r .login)
          echo "Authenticated GitHub user: $AUTHENTICATED_USER"
          echo "::set-output name=authenticated_user::$AUTHENTICATED_USER"
        shell: bash

      - name: Check CODEOWNERS
        run: |
          # Get the authenticated GitHub user
          AUTHENTICATED_USER=${{ steps.get_github_user.outputs.authenticated_user }}

          # Check if the authenticated user is in the CODEOWNERS file
          if grep -q "$AUTHENTICATED_USER" .github/CODEOWNERS; then
            echo "Authorized to merge"
          else
            echo "Not authorized to merge"
            exit 1
          fi
        working-directory: ${{ github.workspace }}
