name: Restrict merges to admins

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  restrict-merges:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the user is an admin
        run: |
          if [[ $(gh api users/me/role | jq -r '.role') != 'admin' ]]; then
            echo "Only admins can merge pull requests into the main branch."
            exit 1
          fi

      - name: Merge the pull request
        run: |
          gh pr merge $PR_NUMBER
